//
//  DetailLaunchView.swift
//  SpaceXSwiftUI
//
//  Created by Martin Lukacs on 17/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import SwiftUI
import SDWebImageSwiftUI

struct DetailLaunchView: View {
    @ObservedObject var viewModel: DetailLaunchViewModel
    
    init(with viewModel: DetailLaunchViewModel) {
        self.viewModel = viewModel
    }
    
    init() {
        self.init(with: DependencyInjector.shared.viewModels.detailLaunchViewModel)
    }
    
    var body: some View {
        VStack {
            WebImage(url: URL(string: viewModel.launch?.links.patch.small ?? ""))
                .resizable()
                .renderingMode(.original)
                .transition(.fade(duration: 0.3))
                .aspectRatio(contentMode: .fit)
                .padding()
            Text("Welcome you are on the page of a specific launche")
            Text(viewModel.launch?.name ?? "")
        }
    }
}

struct DetailLaunchView_Previews: PreviewProvider {
    static var previews: some View {
        DetailLaunchView()
    }
}
