//
//  MainAppViewModel.swift
//  SpaceXSwiftUI
//
//  Created by Martin Lukacs on 16/10/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//

import Foundation

typealias MainRoutingContract = RouteToLaunchesContract & RouteToRocketsContract

final class MainAppViewModel: ObservableObject {    
    var router: MainRoutingContract
    
    init(router: MainRoutingContract) {
        self.router = router
    }
}
